"""empty message

Revision ID: 065db9da5369
Revises: 
Create Date: 2019-04-10 02:23:46.924221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065db9da5369'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
