"""add_admin_column

Revision ID: 6d5077bca8e5
Revises: bbb5e6589a81
Create Date: 2019-04-16 06:31:04.045843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6d5077bca8e5"
down_revision = "bbb5e6589a81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("admin", sa.Boolean(), nullable=False))
    op.execute("UPDATE users SET admin=False")
    op.alter_column("users", "admin", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "admin")
    # ### end Alembic commands ###
